// 此文件由vite-plugin-routes自动生成，请勿手动修改

type RouterKey =
  | 'a&b'
  | 'a&b-index'
  | 'home'
  | 'home-index'
  | 'login'
  | 'login-index'
  | 'setting'
  | 'setting-c'
  | 'setting-c-a[id]&b&h[id]'
  | 'setting-c-q[id]&j[code]'
  | 'setting-c-r&y[query]'
  | 'setting-menu'
  | 'setting-role'
  | 'setting-role-config'
  | 'setting-role-config[id]'
  | 'setting-role-list'
  | 'setting-user'