// 此文件由vite-plugin-routes自动生成，请勿手动修改

type RouteRecordName =
  | '404'
  | 'docs'
  | 'docs-es-toolkit'
  | 'docs-naive-ui'
  | 'docs-naive-ui-components'
  | 'docs-pinia'
  | 'docs-pnpm'
  | 'docs-rengar-admin'
  | 'docs-unocss'
  | 'docs-vite'
  | 'docs-vue'
  | 'docs-vueuse'
  | 'example'
  | 'example-href'
  | 'example-keep-alive'
  | 'home'
  | 'login'
  | 'setting'
  | 'setting-menu'
  | 'setting-role'
  | 'setting-role-config'
  | 'setting-role-list'
  | 'setting-user'
