// Auto-generated by vite-plugin-generate-routes
export const routes = [
  {
    "path": "/home",
    "name": "home",
    "children": [
      {
        "path": "/home",
        "name": "home-index",
        "component": "() => import('@/views/home\\index.vue')"
      }
    ]
  },
  {
    "path": "/user",
    "name": "user",
    "children": [
      {
        "path": "/user/add",
        "name": "user-add",
        "children": [
          {
            "path": "/user/add/[id]",
            "name": "user-add-[id]",
            "component": "() => import('@/views/user\\add\\[id].vue')"
          }
        ]
      },
      {
        "path": "/user/list",
        "name": "user-list",
        "children": [
          {
            "path": "/user/list",
            "name": "user-list-index",
            "component": "() => import('@/views/user\\list\\index.vue')"
          }
        ]
      }
    ]
  }
]