name: 打包部署流程

on:
  push:
    branches: [main]

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: write

jobs:
  main-build:
    name: 打包工作
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build project
        run: |
          npm install
          npm run build
    
  main-deploy:
    name: 部署工作
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
